from pathlib import Path

_HERE    = Path(__file__).parent   # model4_mlpmixer/
_PROJECT = _HERE.parent            # project root

# shared data lives at the project root, generated by model1_cnn/data_exploration.py
DATA_ROOT = _PROJECT / "data"

METADATA_CSV          = DATA_ROOT / "all_labels.csv"
IMAGE_DIR             = DATA_ROOT / "classification_data"
FILTERED_METADATA_CSV = DATA_ROOT / "filtered_metadata.csv"
CLASS_MAP_JSON        = DATA_ROOT / "class_map.json"

CHECKPOINT_DIR        = _HERE / "checkpoints"
BEST_MODEL_PATH       = CHECKPOINT_DIR / "best_model.pth"
OUTPUT_DIR            = _HERE / "outputs"
CONFUSION_MATRIX_PATH = OUTPUT_DIR / "confusion_matrix.png"

# column names in all_labels.csv
COL_IMAGE_PATH = "image_path"
COL_LABEL      = "label_code_id"

REQUIRED_COLS_NULLCHECK = ["image_path", "label", "is_ref", "is_front"]
SUBFOLDER_FILTER        = "segmented_nih_pills_224"

NUM_CLASSES = 10

TRAIN_RATIO = 0.70
VAL_RATIO   = 0.15
TEST_RATIO  = 0.15
RANDOM_SEED = 42

IMAGE_SIZE    = 224
IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD  = [0.229, 0.224, 0.225]

# MLP-Mixer specific
# 224 / 16 = 14  →  14 × 14 = 196 patches per image
PATCH_SIZE        = 16
HIDDEN_DIM        = 256   # patch embedding dimension (C in the paper)
NUM_MIXER_LAYERS  = 6     # number of Mixer layers (depth)
TOKENS_MLP_DIM    = 128   # hidden dim of the token-mixing MLP
CHANNELS_MLP_DIM  = 512   # hidden dim of the channel-mixing MLP

BATCH_SIZE    = 32
NUM_EPOCHS    = 20
LEARNING_RATE = 1e-3
DROPOUT_RATE  = 0.1

# augmentation (training only)
ROTATION_DEGREES        = 15
COLOR_JITTER_BRIGHTNESS = 0.3
COLOR_JITTER_CONTRAST   = 0.3

NUM_VIZ_SAMPLES = 5
